### ISSUE TITLE
Randomize the questions

### ISSUE THREAD

**Issue by K00213234** [Kazuma2019-tech/QuizApplication#3]
I would add an array of int representing the indexes of the questions

https://github.com/Kazuma2019-tech/QuizApplication/blob/704ff3150cde1caba885312fb6a44d0a32bb7f4b/src/main/java/com/kazuma/quizapplication/QuizJFrame.java#L15-L26
On line 27 I would add `private final int[] questionOrder = new int[questionBank.length];`

Then fill the array element from 0 to the size of the array
Then randomize them.
Then change this line 
https://github.com/Kazuma2019-tech/QuizApplication/blob/704ff3150cde1caba885312fb6a44d0a32bb7f4b/src/main/java/com/kazuma/quizapplication/QuizJFrame.java#L126

to use the contents questionOrder like 
`int questionNumber = questionOrder[questionIndex];`
`questionJTextField.setText(questionBank[questionNumber]);`

**Comment by Kazuma2019-tech** [comment]
implemented
